package com.pechterev.statemachine.events;

/**
 * События для перехода заявки по статусам
 */
public enum IdentInquiryStateEvent {

    PRE_VALIDATION_CHECKS_PASSED,
    EPK_CHECK_PASSED,
    STOPLIST_CHECK_PASSED,
    CHECK_FAILED,
    INTERNAL_CHECK_STARTED,
    INTERNAL_CHECK_PASSED,
    IDENTIFICATION_STARTED,
    NOT_CONFIRMED_ESIA_PROFILE,
    SCOPES_DONT_MATCH,
    PROFILE_DATA_RECEIVED,
    INTERNAL_PROFILE_CHECKS_STARTED,
    INTERNAL_PROFILE_CHECKS_FAILED,
    INTERNAL_PROFILE_CHECKS_FINISHED,
    EXTERNAL_PROFILE_CHECKS_FAILED,
    EXTERNAL_PROFILE_CHECKS_FINISHED,
    NO_ATTEMPTS_LEFT,
    INTERNAL_CHECK_SUCCESS,
    EXPIRED,
    DELETED

}

